// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fufzcjychemdijvhbozz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1ZnpjanljaGVtZGlqdmhib3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNjg2NTQsImV4cCI6MjA2Nzg0NDY1NH0.V3TVWE8Rjh_Z8RE4jqecx2547T0WAgc22mDsR3kxsnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});